# Generated by Django 6.0.5 on 2026-06-08 20:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='documento_meio_ambiente',
            field=models.FileField(blank=True, null=True, upload_to='temp/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='documento_sanitario',
            field=models.FileField(blank=True, null=True, upload_to='temp/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='oficio_bombeiro',
            field=models.FileField(blank=True, null=True, upload_to='temp/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
