# Generated by Django 6.0.5 on 2026-06-23 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0002_alter_solicitacao_documento_meio_ambiente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='comandante_opo',
            field=models.CharField(blank=True, default='HELIO NERY DOS SANTOS JUNIOR - CAP PM, Mat. 30581994', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='efetivo_opo',
            field=models.TextField(blank=True, default='01 (uma) Guarnição a critério do Coordenador de Área. Modalidade: Patrulhamento. Processo: Motorizado.', null=True),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='numero_opo',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='opo_pdf',
            field=models.FileField(blank=True, null=True, upload_to='opos/'),
        ),
    ]
