# Generated by Django 6.0.5 on 2026-06-23 03:52

import apps.solicitacoes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0003_solicitacao_comandante_opo_solicitacao_efetivo_opo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='opo_pdf',
            field=models.FileField(blank=True, null=True, upload_to=apps.solicitacoes.models.pasta_opo),
        ),
    ]
